"""phase1_canonical_schema

Revision ID: 58ecca5e38a3
Revises: 
Create Date: 2026-07-20 11:38:02.423394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58ecca5e38a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_identity',
    sa.Column('face_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("lifecycle_status = 'anonymous' OR (name IS NOT NULL AND length(name) > 0)", name=op.f('ck_face_identity_face_identity_known_name_check')),
    sa.CheckConstraint("lifecycle_status = 'known' OR (name IS NULL AND metadata = '{}'::jsonb)", name=op.f('ck_face_identity_face_identity_anonymous_pii_check')),
    sa.CheckConstraint("lifecycle_status IN ('anonymous', 'known')", name=op.f('ck_face_identity_face_identity_status_check')),
    sa.PrimaryKeyConstraint('face_id', name=op.f('pk_face_identity'))
    )
    op.create_index('ix_face_identity_active_null_deleted', 'face_identity', ['deleted_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_face_identity_status_active', 'face_identity', ['lifecycle_status', 'is_active'], unique=False)
    op.create_table('process_record',
    sa.Column('process_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('process_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('face_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("process_type IN ('recognize', 'enroll', 'update', 'delete')", name=op.f('ck_process_record_process_record_type_check')),
    sa.CheckConstraint("status IN ('started', 'completed', 'failed')", name=op.f('ck_process_record_process_record_status_check')),
    sa.PrimaryKeyConstraint('process_id', name=op.f('pk_process_record'))
    )
    op.create_index('ix_process_record_created_at', 'process_record', ['created_at'], unique=False)
    op.create_index('ix_process_record_status', 'process_record', ['status'], unique=False)
    op.create_table('face_sample',
    sa.Column('sample_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('face_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('detector_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('alignment_version', sa.String(length=64), nullable=False),
    sa.Column('preprocess_version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("lifecycle_state IN ('pending', 'blob_ready', 'indexed', 'active', 'inactive', 'failed')", name=op.f('ck_face_sample_face_sample_lifecycle_state_check')),
    sa.ForeignKeyConstraint(['face_id'], ['face_identity.face_id'], name=op.f('fk_face_sample_face_id_face_identity')),
    sa.PrimaryKeyConstraint('sample_id', name=op.f('pk_face_sample')),
    sa.UniqueConstraint('bucket', 'object_key', name='uq_face_sample_bucket_object_key')
    )
    op.create_index('ix_face_sample_active_lifecycle', 'face_sample', ['is_active', 'lifecycle_state'], unique=False)
    op.create_index('ix_face_sample_face_id', 'face_sample', ['face_id'], unique=False)
    op.create_table('process_event',
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('process_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('sanitized_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process_record.process_id'], name=op.f('fk_process_event_process_id_process_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_process_event'))
    )
    op.create_index('ix_process_event_created_at', 'process_event', ['created_at'], unique=False)
    op.create_index('ix_process_event_event_type', 'process_event', ['event_type'], unique=False)
    op.create_index('ix_process_event_process_id', 'process_event', ['process_id'], unique=False)
    op.create_table('recognition_result',
    sa.Column('result_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('process_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('detection_ordinal', sa.Integer(), nullable=False),
    sa.Column('face_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status_snapshot', sa.String(length=16), nullable=False),
    sa.Column('name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detector_confidence', sa.Float(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('matched_sample_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_snapshot IN ('known', 'anonymous', 'new_anonymous')", name=op.f('ck_recognition_result_recognition_result_status_snapshot_check')),
    sa.ForeignKeyConstraint(['face_id'], ['face_identity.face_id'], name=op.f('fk_recognition_result_face_id_face_identity')),
    sa.ForeignKeyConstraint(['matched_sample_id'], ['face_sample.sample_id'], name=op.f('fk_recognition_result_matched_sample_id_face_sample')),
    sa.ForeignKeyConstraint(['process_id'], ['process_record.process_id'], name=op.f('fk_recognition_result_process_id_process_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_recognition_result')),
    sa.UniqueConstraint('process_id', 'detection_ordinal', name='uq_recognition_result_process_ordinal')
    )
    op.create_index('ix_recognition_result_face_id', 'recognition_result', ['face_id'], unique=False)
    op.create_index('ix_recognition_result_process_id', 'recognition_result', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recognition_result_process_id', table_name='recognition_result')
    op.drop_index('ix_recognition_result_face_id', table_name='recognition_result')
    op.drop_table('recognition_result')
    op.drop_index('ix_process_event_process_id', table_name='process_event')
    op.drop_index('ix_process_event_event_type', table_name='process_event')
    op.drop_index('ix_process_event_created_at', table_name='process_event')
    op.drop_table('process_event')
    op.drop_index('ix_face_sample_face_id', table_name='face_sample')
    op.drop_index('ix_face_sample_active_lifecycle', table_name='face_sample')
    op.drop_table('face_sample')
    op.drop_index('ix_process_record_status', table_name='process_record')
    op.drop_index('ix_process_record_created_at', table_name='process_record')
    op.drop_table('process_record')
    op.drop_index('ix_face_identity_status_active', table_name='face_identity')
    op.drop_index('ix_face_identity_active_null_deleted', table_name='face_identity', postgresql_where='deleted_at IS NULL')
    op.drop_table('face_identity')
    # ### end Alembic commands ###
